name: passenger_app
description: Passenger App for Live Bus Tracking
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  provider: ^6.1.2
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
flutter:
  uses-material-design: true
