// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCusjHeHbUIiPf_c5L9AxjbJ8D-e6-AmIE',
    appId: '1:528506463151:web:fc8a2b5a0405492d2fc55a',
    messagingSenderId: '528506463151',
    projectId: 'smart-bus-33f6a',
    authDomain: 'smart-bus-33f6a.firebaseapp.com',
    storageBucket: 'smart-bus-33f6a.firebasestorage.app',
    measurementId: 'G-H38WY40DNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMVB7qmdvb2XBO2eRiOilyLqEYnTT-nmI',
    appId: '1:528506463151:android:dbe1c70f018c2e5c2fc55a',
    messagingSenderId: '528506463151',
    projectId: 'smart-bus-33f6a',
    storageBucket: 'smart-bus-33f6a.firebasestorage.app',
  );
}
